import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import setupLocatorUI from '@locator/runtime'

if (process.env.NODE_ENV === 'development') {
  console.log('setupLocatorUI')
  setupLocatorUI()
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: '基于混合搜索的影搜小助手',
  description: 'Generated by create next app',
  icons: {
    icon: '/oceanbase.svg',
    shortcut: '/oceanbase.svg',
    apple: '/oceanbase.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
